// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: games.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (code, level, status)
VALUES ($1, $2, $3)
RETURNING id, code, level, status, created_at, updated_at
`

type CreateGameParams struct {
	Code   string
	Level  string
	Status string
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.Code, arg.Level, arg.Status)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameByCode = `-- name: GetGameByCode :one
SELECT id, code, level, status, created_at, updated_at FROM games
WHERE code = $1
`

func (q *Queries) GetGameByCode(ctx context.Context, code string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByCode, code)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Level,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
