// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: questions.sql

package database

import (
	"context"
)

const getRandomQuestionByLevel = `-- name: GetRandomQuestionByLevel :one
SELECT id, content FROM questions
WHERE level = $1
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomQuestionByLevelRow struct {
	ID      int64
	Content string
}

func (q *Queries) GetRandomQuestionByLevel(ctx context.Context, level string) (GetRandomQuestionByLevelRow, error) {
	row := q.db.QueryRow(ctx, getRandomQuestionByLevel, level)
	var i GetRandomQuestionByLevelRow
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}
