// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rounds.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (
  game_id, question_id, current_player_id, is_joker, status
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, game_id, question_id, current_player_id, is_joker, status, created_at
`

type CreateRoundParams struct {
	GameID          int64
	QuestionID      int64
	CurrentPlayerID int64
	IsJoker         pgtype.Bool
	Status          string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.GameID,
		arg.QuestionID,
		arg.CurrentPlayerID,
		arg.IsJoker,
		arg.Status,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.CurrentPlayerID,
		&i.IsJoker,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoundsByGame = `-- name: DeleteRoundsByGame :exec
DELETE FROM rounds
WHERE game_id = $1
`

func (q *Queries) DeleteRoundsByGame(ctx context.Context, gameID int64) error {
	_, err := q.db.Exec(ctx, deleteRoundsByGame, gameID)
	return err
}

const getRoundByID = `-- name: GetRoundByID :one
SELECT id, game_id, question_id, current_player_id, is_joker, status, created_at FROM rounds
WHERE id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByID, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.CurrentPlayerID,
		&i.IsJoker,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listRoundsByGame = `-- name: ListRoundsByGame :many
SELECT id, game_id, question_id, current_player_id, is_joker, status, created_at FROM rounds
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRoundsByGame(ctx context.Context, gameID int64) ([]Round, error) {
	rows, err := q.db.Query(ctx, listRoundsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.QuestionID,
			&i.CurrentPlayerID,
			&i.IsJoker,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRoundAsJoker = `-- name: MarkRoundAsJoker :exec
UPDATE rounds
SET is_joker = TRUE, status = 'revealed'
WHERE id = $1
`

func (q *Queries) MarkRoundAsJoker(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRoundAsJoker, id)
	return err
}

const updateRoundStatus = `-- name: UpdateRoundStatus :exec
UPDATE rounds
SET status = $2
WHERE id = $1
`

type UpdateRoundStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error {
	_, err := q.db.Exec(ctx, updateRoundStatus, arg.ID, arg.Status)
	return err
}
